services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
      POSTGRES_DB: yourdbname
    ports:
      - "5432:5432"
